service: samaj-darshan

image: paraspace32/samaj-darshan

ssh:
  user: paras
  keys:
    - ~/.ssh/google_compute_engine

servers:
  web:
    - 34.14.172.86

proxy:
  ssl: true
  host: www.samaj-darshan.com
  app_port: 3000

registry:
  server: ghcr.io
  username: paraspace32
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SAMAJ_DARSHAN_DATABASE_PASSWORD
    - GCS_PROJECT_ID
    - GCS_BUCKET
    - GCS_CREDENTIALS
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_LEVEL: info
    DB_HOST: samaj-darshan-db
    RAILS_ASSUME_SSL: "true"
    RAILS_FORCE_SSL: "true"
    GA_MEASUREMENT_ID: "G-KJBW0359PV"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "samaj_darshan_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
  remote: ssh://paras@34.14.148.194

accessories:
  db:
    image: postgres:16
    host: 34.14.148.194
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: samaj_darshan
        POSTGRES_DB: samaj_darshan_production
      secret:
        - SAMAJ_DARSHAN_DATABASE_PASSWORD
    directories:
      - samaj_darshan_pgdata:/var/lib/postgresql/data
